Compress images and enable gzip
saberespoder/urwelcome pull request #11
Opened 2017-03-13 15:09 UTC by FanaHOVA

2017-03-13 15:24 UTC, skatkov requested changes
Since we're talking about speed imrovements, i woudl suggest:
- Moving JS code to bottom of a page, so it would start loading after page is rendered.
- Changing dimension for face shoots - lady is 2800 pixels wide. Seems crazy good quality for a webpage :P

2017-03-13 15:24 UTC, skatkov commented on views/layout.slim
>      script src="assets/javascripts/scripts.js"
Recommend to try moving these script to bottom of a page. It will speed up initial page load dramatically.

2017-03-14 12:10 UTC, FanaHOVA commented on views/layout.slim
>      script src="assets/javascripts/scripts.js"
@skatkov I don't understand, they already are at the bottom at the page?

2017-03-14 12:16 UTC, FanaHOVA commented on views/layout.slim
>      script src="assets/javascripts/scripts.js"
@skatkov Ah you meant at the bottom of the list, got it!

2017-03-16 20:53 UTC, skatkov approved these changes

2017-03-17 10:43 UTC, merged